# Generated by Django 4.2 on 2024-03-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.PositiveIntegerField(verbose_name='сумма пожертвования')),
                ('payment_link', models.URLField(blank=True, null=True, verbose_name='ссылка на оплату')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id сессии оплаты')),
            ],
            options={
                'verbose_name': 'Пожертвования',
                'verbose_name_plural': 'Пожертвования',
            },
        ),
    ]
