# Generated by Django 4.2 on 2024-03-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_link',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
